services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yesenia-app
    container_name: yesenia-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
    networks:
      - yesenia-network
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: yesenia-nginx
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - .:/var/www
      - ./docker/conf:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - yesenia-network

networks:
  yesenia-network:
    driver: bridge